name: Sync ReadMe Docs 🦉

on:
  push:
    branches:
      - main

jobs:
  readme-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo 📚
        uses: actions/checkout@v3

      - name: Run `docs` command 🚀
        uses: readmeio/rdme@v10
        with:
          rdme: docs upload source/guides/ --key=${{ secrets.README_API_KEY }} --branch=1.0
