name: Sync ReadMe Changelogs 🦉

on:
  push:
    branches:
      - main

jobs:
  readme-changelogs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo 📚
        uses: actions/checkout@v3

      - name: Run `changelogs` command 🚀
        uses: readmeio/rdme@v8
        with:
          rdme: changelogs source/changelogs/ --key=${{ secrets.README_API_KEY }}
